name: Demo App Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install playwright browser
        run: pnpm dlx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: pnpm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: demo/playwright-report/
          retention-days: 30
